- name: Install asdf-vm
  become: yes
  apt:
    name: "git"
    state: present

- name: Download and install asdf-vm
  become: yes
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: '/home/{{ base_user }}/.asdf'
    clone: yes
    update: yes
    version: master

- name: Add asdf to .zshrc
  become: yes
  lineinfile:
    path: "/home/{{ base_user }}/.zshrc"
    regexp: '^# added by Ansible to configure asdf-vm'
    line: 'export PATH="$HOME/.asdf/bin:$PATH"'
  notify:
    - Reload shell

- name: Add the init script to .zshrc
  become: yes
  lineinfile:
    path: "/home/{{ base_user }}/.zshrc"
    regexp: '^# added by Ansible to initialize asdf-vm'
    line: '. $HOME/.asdf/asdf.sh'
  notify:
    - Reload shell

- name: Reload shell
  become: yes
  shell: source /home/{{ base_user }}/.zshrc
  when: base_user != 'root'
