- name: Add RVM's GPG key
  shell: gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  args:
    executable: /bin/bash

- name: Install RVM binaries
  shell: curl -sSL https://get.rvm.io | bash -s stable
  args:
    executable: /bin/bash

- name: Install Ruby 2.7
  shell: "rvm install {{ ruby_version }}"
  args:
    executable: /bin/bash
