- name: Ensure apt-transport-https is installed
  become: yes
  apt:
    name: apt-transport-https
    state: present

- name: Add Spotify's GPG key
  tags: streaming
  apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present

- name: Set up Spotify repository
  tags: streaming
  apt_repository:
    repo: "deb [arch=amd64] https://repository.spotify.com stable non-free"
    state: present

- name: Install Spotify client
  tags: streaming
  apt:
    update_cache: yes
    name: spotify-client
    state: present
