- name: Clone NVM git repository
  tags: installation, node
  git:
    repo: "{{ nvm_repo_url }}"
    dest: "{{ nvm_path }}"

- name: Install node and set version
  tags: installation, node
  shell: "source {{ nvm_path }}/nvm.sh && nvm install {{ node_version }}"
  args:
    executable: /bin/bash
