base_user: gleidson
base_packages:
  - curl
  - flameshot
  - gnupg2
  - htop
  - neofetch
  - tmux
  - vlc
  - zsh

docker_prerequisite_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
docker_service: docker
docker_user: "{{ base_user }}"
docker_group: docker

ohmyzsh_plugin_base_url: "https://github.com/zsh-users/" 
ohmyzsh_plugin_dir: "/home/{{ base_user }}/.oh-my-zsh/custom/plugins/"
ohmyzsh_plugins:
  - repo_url: "{{ ohmyzsh_plugin_base_url }}/zsh-syntax-highlighting.git"
    dest: "{{ ohmyzsh_plugin_dir }}/zsh-syntax-highlighting"
  - repo_url: "{{ ohmyzsh_plugin_base_url }}/zsh-autosuggestions.git"
    dest: "{{ ohmyzsh_plugin_dir }}/zsh-autosuggestions"


nvm_repo_url: https://github.com/creationix/nvm.git
nvm_path: "/home/{{ base_user }}/.nvm"
node_version: 16

ruby_version: 2.7

cursor_download_url: "https://downloads.cursor.com/production/031e7e0ff1e2eda9c1a0f5df67d44053b059c5df/linux/x64/Cursor-1.2.1-x86_64.AppImage"
